In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv(r'C:\Users\nnoar\OneDrive\Desktop\Project 1\Project1_Team3\BRFSS_2019_data.csv')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223058 entries, 0 to 223057
Data columns (total 27 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Year                        223058 non-null  int64
 1   Locationabbr                223058 non-null  object
 2   Locationdesc                223058 non-null  object
 3   Class                       223058 non-null  object
 4   Topic                       223058 non-null  object
 5   Question                    223058 non-null  object
 6   Response                    223058 non-null  object
 7   Break_Out                   223058 non-null  object
 8   Break_Out_Category          223058 non-null  object
 9   Sample_Size                 223058 non-null  object
 10  Data_value                  177262 non-null  float64
 11  Confidence_limit_Low        176922 non-null  float64
 12  Confidence_limit_High       176922 non-null  float64
 13  Display_order               223058 non-null  int64
 14  Data_value_unit             223058 non-null  object
 15  Data_value_type             223058 non-null  object
 16  Data_Value_Footnote_Symbol  45796 non-null   object
 17  Data_Value_Footnote         45796 non-null   object
 18  DataSource                  223058 non-null  object
 19  ClassId                     223058 non-null  object
 20  TopicId                     223058 non-null  object
 21  LocationID                  223058 non-null  int64
 22  BreakoutID                  223058 non-null  object
 23  BreakOutCategoryID          223058 non-null  object
 24  QuestionID                  223058 non-null  object
 25  ResponseID                  223058 non-null  object
 26  GeoLocation                 222716 non-null  object
dtypes: float64(3), int64(3), object(21)
memory usage: 45.9+ MB

In [7]:
data['Question'].value_counts()

What is your employment status?                                                                                                                                                 10832
What is your marital status?                                                                                                                                                     8124
How many children live in your household? (variable calculated from one or more BRFSS questions)                                                                                 8124
What is your race/ethnicity?                                                                                                                                                     7504
About how long has it been since you last visited a doctor for a routine checkup?                                                                                                6770
How is your general health?                                                                                                                                                      6770
What is your age?                                                                                                                                                                6252
What is your annual household income?                                                                                                                                            5470
Have you ever been told by a doctor that you have diabetes?                                                                                                                      5416
Since 2005, have you had a tetanus shot?                                                                                                                                         5416
Four Level Smoking Status (variable calculated from one or more BRFSS questions)                                                                                                 5416
Weight classification by Body Mass Index (BMI) (variable calculated from one or more BRFSS questions)                                                                            5416
What is the highest grade or year of school you completed?                                                                                                                       4584
Do you have one person you think of as your personal doctor or health care provider?                                                                                             4062
Days when mental health status not good (variable calculated from one or more BRFSS questions)                                                                                   4062
Adults who have had their blood cholesterol checked within the last five years (variable calculated from one or more BRFSS questions)                                            4062
Days when physical health status not good (variable calculated from one or more BRFSS questions)                                                                                 4062
Do arthritis or joint symptoms now affect whether you work? (variable calculated from one or more BRFSS questions)                                                               4062
Do you currently use chewing tobacco, snuff, or snus?                                                                                                                            4062
Are you now limited in any way in any of your usual activities because of arthritis? (variable calculated from one or more BRFSS questions)                                      4062
Do you own or rent your home?                                                                                                                                                    4062
Participated in muscle strengthening exercises two or more times per week (variable calculated from one or more BRFSS questions)                                                 2708
Ever told you had a heart attack (myocardial infarction)?                                                                                                                        2708
Respondents that have ever reported having coronary heart disease (chd) or myocardial infarction (mi) (variable calculated from one or more BRFSS questions)                     2708
Adults who have had their blood cholesterol checked and have been told it was high (variable calculated from one or more BRFSS questions)                                        2708
Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?                                                                            2708
Do you have difficulty dressing or bathing?                                                                                                                                      2708
Adults who have been told they have high blood pressure (variable calculated from one or more BRFSS questions)                                                                   2708
Health Status (variable calculated from one or more BRFSS questions)                                                                                                             2708
Adults who have ever been told they have asthma (variable calculated from one or more BRFSS questions)                                                                           2708
Do you have any kind of health care coverage?                                                                                                                                    2708
Ever told you had skin cancer?                                                                                                                                                   2708
Ever told you had a stroke?                                                                                                                                                      2708
Consumed vegetables less than one time per day (variable calculated from one or more BRFSS questions)                                                                            2708
Participated in 150 minutes or more of Aerobic Physical Activity per week (variable calculated from one or more BRFSS questions)                                                 2708
Have you ever served on active duty in the United States Armed Forces?                                                                                                           2708
Are you blind or do you have serious difficulty seeing, even when wearing glasses?                                                                                               2708
Ever told you have kidney disease?                                                                                                                                               2708
Binge drinkers (males having five or more drinks on one occasion, females having four or more drinks on one occasion) (variable calculated from one or more BRFSS questions)     2708
Adults who reported being deaf                                                                                                                                                   2708
Do you have difficulty doing errands alone?                                                                                                                                      2708
Do you have serious difficulty concentrating, remembering, or making decisions?                                                                                                  2708
Ever told you had angina or coronary heart disease?                                                                                                                              2708
Ever told you have COPD?                                                                                                                                                         2708
Have you ever been tested for HIV?                                                                                                                                               2708
Do you have serious difficulty walking or climbing stairs?                                                                                                                       2708
Participated in enough Aerobic and Muscle Strengthening exercises to meet guidelines (variable calculated from one or more BRFSS questions)                                      2708
Adults who have been told they have arthritis (variable calculated from one or more BRFSS questions)                                                                             2708
Ever told you that you have a form of depression?                                                                                                                                2708
Adults who have been told they currently have asthma (variable calculated from one or more BRFSS questions)                                                                      2708
Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week) (variable calculated from one or more BRFSS questions)         2708
Consumed fruit less than one time per day (variable calculated from one or more BRFSS questions)                                                                                 2708
Adults who are current smokers (variable calculated from one or more BRFSS questions)                                                                                            2708
During the past month, did you participate in any physical activities? (variable calculated from one or more BRFSS questions)                                                    2708
Ever told you had any other types of cancer?                                                                                                                                     2708
Adults who have had at least one drink of alcohol within the past 30 days                                                                                                        2708
Adults aged 18-64 who have any kind of health care coverage (variable calculated from one or more BRFSS questions)                                                               2604
Gender of respondent                                                                                                                                                             2500
Adults aged 65+ who have ever had a pneumonia vaccination (variable calculated from one or more BRFSS questions)                                                                 2292
Adults aged 65+ who have had a flu shot within the past year (variable calculated from one or more BRFSS questions)                                                              2292
Name: Question, dtype: int64

In [8]:
data['Topic'].value_counts()

Disability status          13540
Arthritis                  10832
Employment                 10832
Cardiovascular Disease     10832
Healthy Days                8124
Marital Status              8124
Number of Children          8124
Race                        7504
Last Checkup                6770
Overall Health              6770
Age                         6252
Income                      5470
Smoker Status               5416
Diabetes                    5416
Asthma                      5416
Tetanus Shot                5416
BMI Categories              5416
Education                   4584
Rent/Own Home               4062
Personal Care Provider      4062
Smokeless Tobacco           4062
Cholesterol Checked         4062
Exercise                    2708
Aerobic Activity            2708
Veteran Status              2708
Cholesterol High            2708
Health Care Coverage        2708
Fair or Poor Health         2708
Current Smoker Status       2708
Health Care Cost            2708
Heavy Drinking              2708
Fruit Consumption           2708
Binge Drinking              2708
Skin Cancer                 2708
Alcohol Consumption         2708
Depression                  2708
Hearing                     2708
High Blood Pressure         2708
Vegetable Consumption       2708
Kidney                      2708
Strength Activity           2708
HIV Test                    2708
COPD                        2708
Physical Activity Index     2708
Other Cancer                2708
Under 65 Coverage           2604
Sex                         2500
Pneumonia Vaccination       2292
Flu Shot                    2292
Name: Topic, dtype: int64

In [10]:
topics = ['Employment', 'Marital Status','Race','Age','Income','Education','Under 65 Coverage','Sex','Health Care Coverage','Health Care Cost','Depression', 'Healthy Days']

In [22]:
new_data = data.loc[data['Topic'].isin(topics)]
new_data = new_data[new_data['Break_Out'] == 'Overall']
new_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2862 entries, 42 to 223023
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Year                        2862 non-null   int64
 1   Locationabbr                2862 non-null   object
 2   Locationdesc                2862 non-null   object
 3   Class                       2862 non-null   object
 4   Topic                       2862 non-null   object
 5   Question                    2862 non-null   object
 6   Response                    2862 non-null   object
 7   Break_Out                   2862 non-null   object
 8   Break_Out_Category          2862 non-null   object
 9   Sample_Size                 2862 non-null   object
 10  Data_value                  2799 non-null   float64
 11  Confidence_limit_Low        2695 non-null   float64
 12  Confidence_limit_High       2695 non-null   float64
 13  Display_order               2862 non-null   int64
 14  Data_value_unit             2862 non-null   object
 15  Data_value_type             2862 non-null   object
 16  Data_Value_Footnote_Symbol  63 non-null     object
 17  Data_Value_Footnote         63 non-null     object
 18  DataSource                  2862 non-null   object
 19  ClassId                     2862 non-null   object
 20  TopicId                     2862 non-null   object
 21  LocationID                  2862 non-null   int64
 22  BreakoutID                  2862 non-null   object
 23  BreakOutCategoryID          2862 non-null   object
 24  QuestionID                  2862 non-null   object
 25  ResponseID                  2862 non-null   object
 26  GeoLocation                 2756 non-null   object
dtypes: float64(3), int64(3), object(21)
memory usage: 626.1+ KB

In [26]:
new_df = new_data[['Locationabbr'
,'Locationdesc',
'Topic',
'Question',
'Response',
'Sample_Size',
'Data_value',
'GeoLocation']]
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2862 entries, 42 to 223023
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Locationabbr  2862 non-null   object
 1   Locationdesc  2862 non-null   object
 2   Topic         2862 non-null   object
 3   Question      2862 non-null   object
 4   Response      2862 non-null   object
 5   Sample_Size   2862 non-null   object
 6   Data_value    2799 non-null   float64
 7   GeoLocation   2756 non-null   object
dtypes: float64(1), object(7)
memory usage: 201.2+ KB

In [45]:
reponses = new_df['Response'].nunique()
states = new_df['Locationdesc'].unique()
reponses

47

In [43]:
df_pivot = new_df.pivot_table(index='Locationdesc',columns='Response',values='Data_value')
df_pivot.head()

Response,"$15,000 - 24,999","$25,000 - 34,999","$35,000 - 49,999","$50,000+",1-13 days when mental health not good,1-13 days when physical health not good,14+ days when mental health not good,14+ days when physical health not good,18-24 years,25-34 years,...,Self-employed,Separated,Some post-H.S.,Student,Unable to work,"White, non-Hispanic",Widowed,Yes,Zero days when mental health not good,Zero days when physical health not good
Locationdesc,,,,,,,,,,,,,,,,,,,,,
Alabama,20.0,10.4,14.6,42.9,24.5,23.4,17.5,16.0,12.2,16.6,...,8.2,3.1,31.7,4.9,13.7,67.5,8.0,52.725,58.0,60.6
Alaska,12.3,8.9,12.5,60.4,24.8,29.0,12.0,9.8,12.8,20.6,...,9.4,2.0,36.3,3.9,5.6,63.6,4.6,52.325,63.1,61.2
All States and DC (median) **,14.9,9.8,13.8,52.7,25.0,24.6,13.8,12.6,12.4,16.9,...,9.3,2.1,31.6,5.1,6.3,73.3,6.8,51.925,61.4,63.1
"All States, DC and Territories (median) **",15.0,9.8,13.8,52.5,24.9,24.6,13.8,12.6,12.4,16.9,...,9.3,2.1,31.4,5.1,6.3,71.9,6.8,51.925,61.4,63.0
Arizona,17.8,10.9,14.5,48.1,25.6,25.6,14.4,13.2,12.5,17.5,...,9.6,2.5,35.0,5.3,6.2,58.4,6.8,49.325,60.0,61.2

In [48]:
state_df = new_df[['Locationdesc','Locationabbr','GeoLocation']].drop_duplicates()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 54 entries, 42 to 217692
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Locationdesc  54 non-null     object
 1   Locationabbr  54 non-null     object
 2   GeoLocation   52 non-null     object
dtypes: object(3)
memory usage: 1.7+ KB

In [50]:
data_cleaning = pd.merge(df_pivot,state_df, on='Locationdesc',how='outer')
data_cleaning.head()

,Locationdesc,"$15,000 - 24,999","$25,000 - 34,999","$35,000 - 49,999","$50,000+",1-13 days when mental health not good,1-13 days when physical health not good,14+ days when mental health not good,14+ days when physical health not good,18-24 years,...,Some post-H.S.,Student,Unable to work,"White, non-Hispanic",Widowed,Yes,Zero days when mental health not good,Zero days when physical health not good,Locationabbr,GeoLocation
0,Alabama,20.0,10.4,14.6,42.9,24.5,23.4,17.5,16.0,12.2,...,31.7,4.9,13.7,67.5,8.0,52.725,58.0,60.6,AL,"(32.84057112200048, -86.63186076199969)"
1,Alaska,12.3,8.9,12.5,60.4,24.8,29.0,12.0,9.8,12.8,...,36.3,3.9,5.6,63.6,4.6,52.325,63.1,61.2,AK,"(64.84507995700051, -147.72205903599973)"
2,All States and DC (median) **,14.9,9.8,13.8,52.7,25.0,24.6,13.8,12.6,12.4,...,31.6,5.1,6.3,73.3,6.8,51.925,61.4,63.1,UW,NaN
3,"All States, DC and Territories (median) **",15.0,9.8,13.8,52.5,24.9,24.6,13.8,12.6,12.4,...,31.4,5.1,6.3,71.9,6.8,51.925,61.4,63.0,US,NaN
4,Arizona,17.8,10.9,14.5,48.1,25.6,25.6,14.4,13.2,12.5,...,35.0,5.3,6.2,58.4,6.8,49.325,60.0,61.2,AZ,"(34.865970280000454, -111.76381127699972)"

In [52]:
data_cleaning.columns

Index(['Locationdesc', '$15,000 - 24,999', '$25,000 - 34,999',
       '$35,000 -  49,999', '$50,000+',
       '1-13 days when mental health not good',
       '1-13 days when physical health not good',
       '14+ days when mental health not good',
       '14+ days when physical health not good', '18-24 years', '25-34 years',
       '35-44 years', '45-54 years', '55-64 years', '65+ years',
       'American Indian or Alaskan native, non-Hispanic',
       'Asian, non-Hispanic', 'Black, non-Hispanic', 'College+', 'Divorced',
       'Employed', 'Female', 'H.S. or G.E.D.', 'Hispanic', 'Homemaker',
       'Less than $15,000', 'Less than H.S.', 'Male', 'Married',
       'Multiracial, non-Hispanic',
       'Native Hawaiian or other Pacific Islander, non-Hispanic',
       'Never married', 'No', 'No work >yr', 'No work< yr',
       'Other race, non-Hispanic', 'Partnered', 'Retired', 'Self-employed',
       'Separated', 'Some post-H.S.', 'Student', 'Unable to work',
       'White, non-Hispanic', 'Widowed', 'Yes',
       'Zero days when mental health not good',
       'Zero days when physical health not good', 'Locationabbr',
       'GeoLocation'],
      dtype='object')

In [55]:
data_cleaning.rename(columns={'Locationdesc':'State', 'Yes':'Depression Diagnosis','No':'No Depression Diagnosis','Locationabbr':'State Code'},inplace=True)
data_cleaning.head()

,State,"$15,000 - 24,999","$25,000 - 34,999","$35,000 - 49,999","$50,000+",1-13 days when mental health not good,1-13 days when physical health not good,14+ days when mental health not good,14+ days when physical health not good,18-24 years,...,Some post-H.S.,Student,Unable to work,"White, non-Hispanic",Widowed,Depression Diagnosis,Zero days when mental health not good,Zero days when physical health not good,State Code,GeoLocation
0,Alabama,20.0,10.4,14.6,42.9,24.5,23.4,17.5,16.0,12.2,...,31.7,4.9,13.7,67.5,8.0,52.725,58.0,60.6,AL,"(32.84057112200048, -86.63186076199969)"
1,Alaska,12.3,8.9,12.5,60.4,24.8,29.0,12.0,9.8,12.8,...,36.3,3.9,5.6,63.6,4.6,52.325,63.1,61.2,AK,"(64.84507995700051, -147.72205903599973)"
2,All States and DC (median) **,14.9,9.8,13.8,52.7,25.0,24.6,13.8,12.6,12.4,...,31.6,5.1,6.3,73.3,6.8,51.925,61.4,63.1,UW,NaN
3,"All States, DC and Territories (median) **",15.0,9.8,13.8,52.5,24.9,24.6,13.8,12.6,12.4,...,31.4,5.1,6.3,71.9,6.8,51.925,61.4,63.0,US,NaN
4,Arizona,17.8,10.9,14.5,48.1,25.6,25.6,14.4,13.2,12.5,...,35.0,5.3,6.2,58.4,6.8,49.325,60.0,61.2,AZ,"(34.865970280000454, -111.76381127699972)"